server:
  port: 8083
spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
recovery:
  default-recipes-path: ${RECOVERY_RECIPES_PATH}
  chats-path: ${RECOVERY_CHATS_PATH}
logging:
  level:
    root: ERROR
    com.belogrudovw.cookingbot: debug
open-ai:
  url:
    base: https://api.openai.com
    version: /v1
    path: /chat/completions
  token: ${OPENAI_TOKEN}
  conversation:
    models:
      cheap: gpt-3.5-turbo-1106
      wise: gpt-4-1106-preview
    temperature: 1.25
    max-tokens: 4000
telegram:
  api-url: https://api.telegram.org/bot
  webhook-url: ${WEBHOOK_URL}
  bot:
    token: ${COOKING_BOT_TOKEN}
    name: ${COOKING_BOT_NAME}
    path: /webhook/
stable-diffusion:
  api-url: https://api.stability.ai/v1/generation/stable-diffusion-v1-6/
  token: ${STABILITY_TOKEN}

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.belogrudovw.cookingbot: info

---
spring:
  config:
    activate:
      on-profile: debug
logging:
  level:
    com.belogrudovw.cookingbot: debug
    org.springframework.web: trace