server:
  port: 8083
spring:
  profiles:
    active: test
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
logging:
  level:
    root: ERROR
    com.belogrudovw.cookingbot: debug
telegram:
  bot:
    token: ${COOKING_BOT_TOKEN}
    name: ${COOKING_BOT_NAME}
    path: /webhook/
  webhook-url: ${WEBHOOK_URL}
  telegram-api-url: https://api.telegram.org/bot